### ISSUE TITLE
병헌아 대댓글 퍼블리싱 없애줘!

### ISSUE THREAD

**Issue by limyeonsang** [4-Every1/Viktor#13]
## 목적
> UI 수정
## 작업 상세 내용
- [x] 병헌이가 글 답변의 댓글과 답변영상의 댓글 퍼블리싱을 없애주길 바라요~
## 참고 사항
파이팅

**Comment by Heonbyeong** [comment]
시러

**Comment by Heonbyeong** [comment]
답변 피드 댓글 ImageButton 삭제했습니다.
